# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PyrrigateConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/PyrrigateConfig.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1bproto/PyrrigateConfig.proto\"\x80\x01\n\rPyrrigateConf\x12+\n\x0egoogleCalendar\x18\x01 \x01(\x0b\x32\x13.GoogleCalendarConf\x12#\n\ncontroller\x18\x02 \x03(\x0b\x32\x0f.ControllerConf\x12\x1d\n\x07routine\x18\x03 \x03(\x0b\x32\x0c.RoutineConf\"Y\n\x12GoogleCalendarConf\x12\x16\n\x0esecretFilePath\x18\x01 \x01(\t\x12\x17\n\x0f\x63redentialsPath\x18\x02 \x01(\t\x12\x12\n\ncalendarId\x18\x03 \x01(\t\"\xa7\x01\n\x0e\x43ontrollerConf\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x04type\x18\x02 \x01(\x0e\x32\x1e.ControllerConf.ControllerType\x12\x11\n\tpinNumber\x18\x03 \x01(\x05\x12\x10\n\x08reversed\x18\x04 \x01(\x08\"6\n\x0e\x43ontrollerType\x12\x08\n\x04NULL\x10\x00\x12\x1a\n\x16\x43ONTROLLER_DIGITAL_PIN\x10\x01\"=\n\x0bRoutineConf\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x06\x61\x63tion\x18\x02 \x03(\x0b\x32\x12.RoutineActionConf\"\xa6\x01\n\x11RoutineActionConf\x12\x31\n\nactionType\x18\x01 \x01(\x0e\x32\x1d.RoutineActionConf.ActionType\x12\x18\n\x10targetController\x18\x02 \x03(\t\x12\x13\n\x0b\x65nabledTime\x18\x03 \x01(\x02\"/\n\nActionType\x12\x08\n\x04NULL\x10\x00\x12\x17\n\x13\x41\x43TION_ENABLE_TIMED\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONTROLLERCONF_CONTROLLERTYPE = _descriptor.EnumDescriptor(
  name='ControllerType',
  full_name='ControllerConf.ControllerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROLLER_DIGITAL_PIN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=367,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLERCONF_CONTROLLERTYPE)

_ROUTINEACTIONCONF_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='RoutineActionConf.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ENABLE_TIMED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=606,
  serialized_end=653,
)
_sym_db.RegisterEnumDescriptor(_ROUTINEACTIONCONF_ACTIONTYPE)


_PYRRIGATECONF = _descriptor.Descriptor(
  name='PyrrigateConf',
  full_name='PyrrigateConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='googleCalendar', full_name='PyrrigateConf.googleCalendar', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='controller', full_name='PyrrigateConf.controller', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routine', full_name='PyrrigateConf.routine', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=160,
)


_GOOGLECALENDARCONF = _descriptor.Descriptor(
  name='GoogleCalendarConf',
  full_name='GoogleCalendarConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secretFilePath', full_name='GoogleCalendarConf.secretFilePath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='credentialsPath', full_name='GoogleCalendarConf.credentialsPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calendarId', full_name='GoogleCalendarConf.calendarId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=251,
)


_CONTROLLERCONF = _descriptor.Descriptor(
  name='ControllerConf',
  full_name='ControllerConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ControllerConf.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ControllerConf.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pinNumber', full_name='ControllerConf.pinNumber', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reversed', full_name='ControllerConf.reversed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLLERCONF_CONTROLLERTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=421,
)


_ROUTINECONF = _descriptor.Descriptor(
  name='RoutineConf',
  full_name='RoutineConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RoutineConf.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='RoutineConf.action', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=484,
)


_ROUTINEACTIONCONF = _descriptor.Descriptor(
  name='RoutineActionConf',
  full_name='RoutineActionConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionType', full_name='RoutineActionConf.actionType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetController', full_name='RoutineActionConf.targetController', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabledTime', full_name='RoutineActionConf.enabledTime', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROUTINEACTIONCONF_ACTIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=653,
)

_PYRRIGATECONF.fields_by_name['googleCalendar'].message_type = _GOOGLECALENDARCONF
_PYRRIGATECONF.fields_by_name['controller'].message_type = _CONTROLLERCONF
_PYRRIGATECONF.fields_by_name['routine'].message_type = _ROUTINECONF
_CONTROLLERCONF.fields_by_name['type'].enum_type = _CONTROLLERCONF_CONTROLLERTYPE
_CONTROLLERCONF_CONTROLLERTYPE.containing_type = _CONTROLLERCONF
_ROUTINECONF.fields_by_name['action'].message_type = _ROUTINEACTIONCONF
_ROUTINEACTIONCONF.fields_by_name['actionType'].enum_type = _ROUTINEACTIONCONF_ACTIONTYPE
_ROUTINEACTIONCONF_ACTIONTYPE.containing_type = _ROUTINEACTIONCONF
DESCRIPTOR.message_types_by_name['PyrrigateConf'] = _PYRRIGATECONF
DESCRIPTOR.message_types_by_name['GoogleCalendarConf'] = _GOOGLECALENDARCONF
DESCRIPTOR.message_types_by_name['ControllerConf'] = _CONTROLLERCONF
DESCRIPTOR.message_types_by_name['RoutineConf'] = _ROUTINECONF
DESCRIPTOR.message_types_by_name['RoutineActionConf'] = _ROUTINEACTIONCONF

PyrrigateConf = _reflection.GeneratedProtocolMessageType('PyrrigateConf', (_message.Message,), dict(
  DESCRIPTOR = _PYRRIGATECONF,
  __module__ = 'proto.PyrrigateConfig_pb2'
  # @@protoc_insertion_point(class_scope:PyrrigateConf)
  ))
_sym_db.RegisterMessage(PyrrigateConf)

GoogleCalendarConf = _reflection.GeneratedProtocolMessageType('GoogleCalendarConf', (_message.Message,), dict(
  DESCRIPTOR = _GOOGLECALENDARCONF,
  __module__ = 'proto.PyrrigateConfig_pb2'
  # @@protoc_insertion_point(class_scope:GoogleCalendarConf)
  ))
_sym_db.RegisterMessage(GoogleCalendarConf)

ControllerConf = _reflection.GeneratedProtocolMessageType('ControllerConf', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERCONF,
  __module__ = 'proto.PyrrigateConfig_pb2'
  # @@protoc_insertion_point(class_scope:ControllerConf)
  ))
_sym_db.RegisterMessage(ControllerConf)

RoutineConf = _reflection.GeneratedProtocolMessageType('RoutineConf', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINECONF,
  __module__ = 'proto.PyrrigateConfig_pb2'
  # @@protoc_insertion_point(class_scope:RoutineConf)
  ))
_sym_db.RegisterMessage(RoutineConf)

RoutineActionConf = _reflection.GeneratedProtocolMessageType('RoutineActionConf', (_message.Message,), dict(
  DESCRIPTOR = _ROUTINEACTIONCONF,
  __module__ = 'proto.PyrrigateConfig_pb2'
  # @@protoc_insertion_point(class_scope:RoutineActionConf)
  ))
_sym_db.RegisterMessage(RoutineActionConf)


# @@protoc_insertion_point(module_scope)
